language: scala
jdk: oraclejdk8
script:
  - sbt "++${TRAVIS_SCALA_VERSION}" "^^${SBT_VERSION}" test scripted
matrix:
  include:
  - env: SBT_VERSION="0.13.15"
    scala: 2.10.6
  - env: SBT_VERSION="1.0.0-M6"
    scala: 2.12.2

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

notifications:
  email:
    on_success: never
